/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tien.ui;

import dao.AccountDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import utils.Auth;

/**
 *
 * @author HP
 */
public class ChangePass extends javax.swing.JPanel {

    AccountDAO dao;

    /**
     * Creates new form dmk
     */
    public ChangePass() {
        initComponents();
        txtPass1.setBackground(new Color(255, 255, 255, 0));
        txtPass.setBackground(new Color(255, 255, 255, 0));
        dao = new AccountDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtPassOld = new model.input();
        lblOld = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPass = new javax.swing.JPasswordField();
        lblnew = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtPass1 = new javax.swing.JPasswordField();
        lblnew1 = new javax.swing.JLabel();
        lblNew1 = new javax.swing.JLabel();
        button2 = new component.Button();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1224, 810));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(487, 444));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 26));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel2);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassOld.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassOldCaretUpdate(evt);
            }
        });
        jPanel2.add(txtPassOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 40));

        lblOld.setBackground(new java.awt.Color(67, 67, 67));
        lblOld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOld.setForeground(new java.awt.Color(199, 199, 199));
        lblOld.setText("   Mật khẩu cũ");
        lblOld.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel2.add(lblOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtPassword (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jPanel1.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(199, 199, 199));
        txtPass.setBorder(null);
        txtPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassCaretUpdate(evt);
            }
        });
        jPanel3.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 40));

        lblnew.setBackground(new java.awt.Color(67, 67, 67));
        lblnew.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnew.setForeground(new java.awt.Color(199, 199, 199));
        lblnew.setText("   Mật khẩu mới");
        jPanel3.add(lblnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        lblNew.setBackground(new java.awt.Color(67, 67, 67));
        lblNew.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNew.setForeground(new java.awt.Color(199, 199, 199));
        lblNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtPassword (1).png"))); // NOI18N
        lblNew.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel3.add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPass1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass1.setForeground(new java.awt.Color(199, 199, 199));
        txtPass1.setBorder(null);
        txtPass1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPass1CaretUpdate(evt);
            }
        });
        jPanel5.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 40));

        lblnew1.setBackground(new java.awt.Color(67, 67, 67));
        lblnew1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnew1.setForeground(new java.awt.Color(199, 199, 199));
        lblnew1.setText("   Nhập lại mật khẩu mới");
        jPanel5.add(lblnew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        lblNew1.setBackground(new java.awt.Color(67, 67, 67));
        lblNew1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNew1.setForeground(new java.awt.Color(199, 199, 199));
        lblNew1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txtPassword (1).png"))); // NOI18N
        lblNew1.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel5.add(lblNew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel5);

        button2.setText("ĐỔI MẬT KHẨU");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button2.setPreferredSize(new java.awt.Dimension(403, 45));
        button2.setSizeSpeed(12.0F);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 5@4x 2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1224, 810));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed

    }//GEN-LAST:event_btnChangeActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

    }//GEN-LAST:event_button1ActionPerformed

    private void txtPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassCaretUpdate
        if (!txtPass.getText().equals("")) {
            lblnew.setText("");
        } else
            lblnew.setText("   Mật khẩu mới");
    }//GEN-LAST:event_txtPassCaretUpdate

    private void txtPassOldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassOldCaretUpdate
        if (!txtPassOld.getText().equals("")) {
            lblOld.setText("");
        } else
            lblOld.setText("   Mật khẩu cũ");
    }//GEN-LAST:event_txtPassOldCaretUpdate

    private void txtPass1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPass1CaretUpdate
        // TODO add your handling code here:
        if (!txtPass1.getText().equals("")) {
            lblnew1.setText("");
        } else
            lblnew1.setText("   Nhập lại mật khẩu mới");
    }//GEN-LAST:event_txtPass1CaretUpdate

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if (!Auth.user.getPassword().equals(txtPassOld.getText()) || txtPassOld.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ sai!");
            txtPassOld.requestFocus();
        } else if (Auth.user.getPassword().equals(txtPassOld.getText())) {
            if (txtPass.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu mới!");
                txtPass.requestFocus();
            } else if (!txtPass1.getText().equals(txtPass.getText()) || txtPass1.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Nhập lại mật khẩu không khớp!");
                txtPass1.requestFocus();
            } else {
                String mk = txtPass.getText();
                String ten = Auth.user.getUserID();
                dao.updatePassword(ten, mk);
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
            }
        }
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblNew1;
    private javax.swing.JLabel lblOld;
    private javax.swing.JLabel lblnew;
    private javax.swing.JLabel lblnew1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    private model.input txtPassOld;
    // End of variables declaration//GEN-END:variables
}
