/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tien.ui;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class dmk extends javax.swing.JPanel {

    /**
     * Creates new form dmk
     */
    public dmk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        input1 = new Tien.ui.input();
        lblOld = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        input2 = new Tien.ui.input();
        lblNew = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        input3 = new Tien.ui.input();
        lblCheck = new javax.swing.JLabel();
        button1 = new Tien.ui.Button();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1224, 810));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(487, 444));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 26));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel2);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input1.setForeground(new java.awt.Color(199, 199, 199));
        input1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                input1CaretUpdate(evt);
            }
        });
        jPanel2.add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 40));

        lblOld.setBackground(new java.awt.Color(67, 67, 67));
        lblOld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOld.setForeground(new java.awt.Color(199, 199, 199));
        lblOld.setText("   Mật khẩu cũ");
        lblOld.setOpaque(true);
        lblOld.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel2.add(lblOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input2.setForeground(new java.awt.Color(199, 199, 199));
        input2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                input2CaretUpdate(evt);
            }
        });
        jPanel3.add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 40));

        lblNew.setBackground(new java.awt.Color(67, 67, 67));
        lblNew.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNew.setForeground(new java.awt.Color(199, 199, 199));
        lblNew.setText("   Mật khẩu mới");
        lblNew.setOpaque(true);
        lblNew.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel3.add(lblNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input3.setForeground(new java.awt.Color(199, 199, 199));
        input3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                input3CaretUpdate(evt);
            }
        });
        jPanel4.add(input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 40));

        lblCheck.setBackground(new java.awt.Color(67, 67, 67));
        lblCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCheck.setForeground(new java.awt.Color(199, 199, 199));
        lblCheck.setText("   Nhập lại mật khẩu");
        lblCheck.setOpaque(true);
        lblCheck.setPreferredSize(new java.awt.Dimension(403, 45));
        jPanel4.add(lblCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel4);

        button1.setText("Đổi mật khẩu");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 5@4x 2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1224, 810));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed

    }//GEN-LAST:event_btnChangeActionPerformed

    private void input1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_input1CaretUpdate
        if (!input1.getText().equals("")) {
            lblOld.setText("");
        } else
            lblOld.setText("   Mật khẩu cũ");
    }//GEN-LAST:event_input1CaretUpdate

    private void input2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_input2CaretUpdate
        if (!input2.getText().equals("")) {
            lblNew.setText("");
        } else {
            lblNew.setText("   Mật khẩu mới");
        }
    }//GEN-LAST:event_input2CaretUpdate

    private void input3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_input3CaretUpdate
        if (!input3.getText().equals("")) {
            lblCheck.setText("");
        } else {
            lblCheck.setText("   Nhập lại mật khẩu");
        }
    }//GEN-LAST:event_input3CaretUpdate

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Tien.ui.Button button1;
    private Tien.ui.input input1;
    private Tien.ui.input input2;
    private Tien.ui.input input3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblOld;
    // End of variables declaration//GEN-END:variables
}
