/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tien.ui;

import javax.swing.JFileChooser;

/**
 *
 * @author HP
 */
public class PanelEditAvt extends javax.swing.JPanel {

    /**
     * Creates new form PanelEditAvt
     */
    public PanelEditAvt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFile = new javax.swing.JLabel();
        lblCam = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFile.setForeground(new java.awt.Color(255, 255, 255));
        lblFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 32.png"))); // NOI18N
        lblFile.setText("Chọn file ảnh");
        lblFile.setPreferredSize(new java.awt.Dimension(136, 24));
        lblFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFileMouseClicked(evt);
            }
        });
        add(lblFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, 30));

        lblCam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCam.setForeground(new java.awt.Color(255, 255, 255));
        lblCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 33.png"))); // NOI18N
        lblCam.setText("Chụp ảnh");
        lblCam.setPreferredSize(new java.awt.Dimension(136, 24));
        lblCam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCamMouseClicked(evt);
            }
        });
        add(lblCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 35 (1).png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited

    }//GEN-LAST:event_jLabel5MouseExited

    private void lblCamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCamMouseClicked
        
    }//GEN-LAST:event_lblCamMouseClicked

    private void lblFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFileMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
    }//GEN-LAST:event_lblFileMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCam;
    private javax.swing.JLabel lblFile;
    // End of variables declaration//GEN-END:variables
}
