/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelMain;

import entity.Song;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import model.borderImage;

/**
 *
 * @author Admin
 */
public class ListSongItemAddSongPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListSongItemAddSongPanel
     */ 
    Song song;
    
    public ListSongItemAddSongPanel() {
        initComponents();
        init();
    }
    
    public ListSongItemAddSongPanel(Song song){
        this.song = song;
        initComponents();
        init();
        lblPosition.setText(String.valueOf(song.getSongID()));
        lblPic.setIcon(song.toIcon());
        lblSongName.setText(song.getNameSong());
        lblWriter.setText( song.getMusician());
        lblSinger.setText(song.getSinger());
    }

    public Song getSong() {
        return song;
    }

    public void setSong(Song song) {
        this.song = song;
    }

    public borderImage getBorderImage1() {
        return lblPic;
    }

    public void setBorderImage1(borderImage borderImage1) {
        this.lblPic = borderImage1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLblDelete() {
        return lblDelete;
    }

    public void setLblDelete(JLabel lblDelete) {
        this.lblDelete = lblDelete;
    }

    public JLabel getLblEdit() {
        return lblEdit;
    }

    public void setLblEdit(JLabel lblEdit) {
        this.lblEdit = lblEdit;
    }

    public JLabel getLblPosition() {
        return lblPosition;
    }

    public void setLblPosition(JLabel lblPosition) {
        this.lblPosition = lblPosition;
    }

    public JLabel getLblSinger() {
        return lblSinger;
    }

    public void setLblSinger(JLabel lblSinger) {
        this.lblSinger = lblSinger;
    }

    public JLabel getLblSongName() {
        return lblSongName;
    }

    public void setLblSongName(JLabel lblSongName) {
        this.lblSongName = lblSongName;
    }

    public JLabel getLblWriter() {
        return lblWriter;
    }

    public void setLblWriter(JLabel lblWriter) {
        this.lblWriter = lblWriter;
    }

    public JPanel getPnlEditMenu() {
        return pnlEditMenu;
    }

    public void setPnlEditMenu(JPanel pnlEditMenu) {
        this.pnlEditMenu = pnlEditMenu;
    }

    public JPanel getPnlSongInfo() {
        return pnlSongInfo;
    }

    public void setPnlSongInfo(JPanel pnlSongInfo) {
        this.pnlSongInfo = pnlSongInfo;
    }
    
    
    
    private void init(){
        setOpaque(false);
        pnlSongInfo.setOpaque(false);
        pnlEditMenu.setOpaque(false);
        
        this.setBackground(new Color(0,0,0,1));
        pnlSongInfo.setBackground(new Color(0,0,0,1));
        pnlEditMenu.setBackground(new Color(0,0,0,1));
        
        lblDelete.setFont(new Font("Inter",Font.PLAIN,22));
        lblEdit.setFont(new Font("Inter",Font.PLAIN,22));
        lblPosition.setFont(new Font("Inter",Font.PLAIN,22));
        lblSinger.setFont(new Font("Inter",Font.PLAIN,22));
        lblSongName.setFont(new Font("Inter",Font.PLAIN,22));
        lblWriter.setFont(new Font("Inter",Font.PLAIN,22));
        
        lblDelete.setForeground(Color.white);
        lblEdit.setForeground(Color.white);
        lblPosition.setForeground(Color.white);
        lblSinger.setForeground(Color.white);
        lblSongName.setForeground(Color.white);
        lblWriter.setForeground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPosition = new javax.swing.JLabel();
        pnlSongInfo = new javax.swing.JPanel();
        lblPic = new model.borderImage();
        lblSongName = new javax.swing.JLabel();
        lblWriter = new javax.swing.JLabel();
        lblSinger = new javax.swing.JLabel();
        pnlEditMenu = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDelete = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 51, 255));
        setMaximumSize(new java.awt.Dimension(1073, 70));
        setMinimumSize(new java.awt.Dimension(1073, 70));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1073, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPosition.setText("1");
        lblPosition.setMaximumSize(new java.awt.Dimension(97, 51));
        lblPosition.setMinimumSize(new java.awt.Dimension(97, 51));
        lblPosition.setName(""); // NOI18N
        lblPosition.setPreferredSize(new java.awt.Dimension(97, 51));
        add(lblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlSongInfo.setMaximumSize(new java.awt.Dimension(315, 50));
        pnlSongInfo.setMinimumSize(new java.awt.Dimension(315, 50));
        pnlSongInfo.setPreferredSize(new java.awt.Dimension(315, 50));
        pnlSongInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPic.setMaximumSize(new java.awt.Dimension(50, 50));
        lblPic.setMinimumSize(new java.awt.Dimension(50, 50));
        lblPic.setSizeImage(new int[] {50, 50});

        javax.swing.GroupLayout lblPicLayout = new javax.swing.GroupLayout(lblPic);
        lblPic.setLayout(lblPicLayout);
        lblPicLayout.setHorizontalGroup(
            lblPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lblPicLayout.setVerticalGroup(
            lblPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlSongInfo.add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblSongName.setText("Midnight");
        lblSongName.setMaximumSize(new java.awt.Dimension(300, 100));
        lblSongName.setName(""); // NOI18N
        pnlSongInfo.add(lblSongName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 17, -1, -1));

        add(pnlSongInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        lblWriter.setText("Taylor Swift");
        lblWriter.setMaximumSize(new java.awt.Dimension(194, 51));
        lblWriter.setMinimumSize(new java.awt.Dimension(194, 51));
        lblWriter.setPreferredSize(new java.awt.Dimension(194, 51));
        add(lblWriter, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        lblSinger.setText("Taylor Swift");
        lblSinger.setMaximumSize(new java.awt.Dimension(194, 51));
        lblSinger.setMinimumSize(new java.awt.Dimension(194, 51));
        lblSinger.setPreferredSize(new java.awt.Dimension(194, 51));
        lblSinger.setVerifyInputWhenFocusTarget(false);
        add(lblSinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        pnlEditMenu.setMaximumSize(new java.awt.Dimension(173, 51));
        pnlEditMenu.setMinimumSize(new java.awt.Dimension(173, 51));
        pnlEditMenu.setPreferredSize(new java.awt.Dimension(173, 51));
        pnlEditMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 13));

        lblEdit.setText("Sửa");
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });
        pnlEditMenu.add(lblEdit);

        jSeparator1.setBackground(new java.awt.Color(199, 199, 199));
        jSeparator1.setForeground(new java.awt.Color(199, 199, 199));
        jSeparator1.setMaximumSize(new java.awt.Dimension(1, 24));
        jSeparator1.setMinimumSize(new java.awt.Dimension(1, 24));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 24));
        pnlEditMenu.add(jSeparator1);

        lblDelete.setText("Xóa");
        pnlEditMenu.add(lblDelete);

        add(pnlEditMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblEditMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private model.borderImage lblPic;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSinger;
    private javax.swing.JLabel lblSongName;
    private javax.swing.JLabel lblWriter;
    private javax.swing.JPanel pnlEditMenu;
    private javax.swing.JPanel pnlSongInfo;
    // End of variables declaration//GEN-END:variables
}
