/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelMain;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import swing.SongList;

/**
 *
 * @author NGUYEN VAN SI
 */
public class SongLovelistPane extends javax.swing.JPanel {

    /**
     * Creates new form SongLovelistPanel
     */
    public SongLovelistPane() {
        initComponents();
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JPanel getPnlSongLovelist() {
        return pnlSongLovelist;
    }

    public void setPnlSongLovelist(JPanel pnlSongLovelist) {
        this.pnlSongLovelist = pnlSongLovelist;
    }

    public SongList getPnlSonglist() {
        return pnlSonglist;
    }

    public void setPnlSonglist(SongList pnlSonglist) {
        this.pnlSonglist = pnlSonglist;
    }

    public JPanel getPnlTitleTable1() {
        return pnlTitleTable1;
    }

    public void setPnlTitleTable1(JPanel pnlTitleTable1) {
        this.pnlTitleTable1 = pnlTitleTable1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlSongLovelist = new javax.swing.JPanel();
        pnlTitleTable1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlSonglist = new swing.SongList();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 57, 234));
        jLabel1.setText("BÀI HÁT YÊU THÍCH");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 12, 360, 40));

        pnlSongLovelist.setOpaque(false);
        pnlSongLovelist.setPreferredSize(new java.awt.Dimension(1073, 400));
        pnlSongLovelist.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        pnlTitleTable1.setOpaque(false);
        pnlTitleTable1.setPreferredSize(new java.awt.Dimension(1073, 59));
        pnlTitleTable1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên bài hát");
        jLabel6.setPreferredSize(new java.awt.Dimension(501, 51));
        pnlTitleTable1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 4, 480, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time");
        jLabel7.setPreferredSize(new java.awt.Dimension(162, 51));
        pnlTitleTable1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 4, 140, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("#");
        jLabel8.setPreferredSize(new java.awt.Dimension(112, 51));
        pnlTitleTable1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 4, 140, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("##");
        jLabel9.setPreferredSize(new java.awt.Dimension(194, 51));
        pnlTitleTable1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 4, 180, -1));

        pnlSongLovelist.add(pnlTitleTable1);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(1073, 3));
        pnlSongLovelist.add(jSeparator1);

        pnlSonglist.setPreferredSize(new java.awt.Dimension(1273, 500));
        pnlSongLovelist.add(pnlSonglist);

        add(pnlSongLovelist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1100, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlSongLovelist;
    private swing.SongList pnlSonglist;
    private javax.swing.JPanel pnlTitleTable1;
    // End of variables declaration//GEN-END:variables
}
