/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package swave;

import java.awt.Color;
import javax.swing.JLabel;
import panelMain.LoadingPane;

/**
 *
 * @author Welcome
 */
public class DialogLoad extends javax.swing.JDialog {

    public String textLoad = "Vui lòng chờ";

    /**
     * Creates new form DialogLoad
     */
    public DialogLoad(java.awt.Frame parent, boolean modal, String textLoad) {
        super(parent, modal);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        lblTextLoad.setText(textLoad);
    }
    
//    public DialogLoad(java.awt.Frame parent, boolean modal, String textLoad) {
//        super(parent, modal);
//        initComponents();
//        this.setBackground(new Color(0, 0, 0, 0));
//        this.setLocationRelativeTo(null);
//        lblTextLoad.setText(textLoad);
//    }

    private void loading() {
        while (true) {
            lblTextLoad.setText(this.textLoad + " .");
            System.out.println(this.textLoad);
            lblTextLoad.setText(this.textLoad + " ..");
            lblTextLoad.setText(this.textLoad + " ...");
        }
    }

    public String getTextLoad() {
        return textLoad;
    }

    public void setTextLoad(String textLoad) {
        this.textLoad = textLoad;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getLblTextLoad() {
        return lblTextLoad;
    }

    public void setLblTextLoad(JLabel lblTextLoad) {
        this.lblTextLoad = lblTextLoad;
    }

    public LoadingPane getLoadingPane1() {
        return loadingPane1;
    }

    public void setLoadingPane1(LoadingPane loadingPane1) {
        this.loadingPane1 = loadingPane1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingPane1 = new panelMain.LoadingPane();
        lblTextLoad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        loadingPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextLoad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTextLoad.setForeground(new java.awt.Color(255, 255, 255));
        lblTextLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextLoad.setText("Vui lòng chờ");
        loadingPane1.add(lblTextLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 500, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loading.gif"))); // NOI18N
        loadingPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogLoad dialog = new DialogLoad(new javax.swing.JFrame(), true, "Đang đăng nhập...");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                dialog.loading();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTextLoad;
    private panelMain.LoadingPane loadingPane1;
    // End of variables declaration//GEN-END:variables
}
