/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing.swavecomponent;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.accessibility.AccessibleContext;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;
import swing.utilcomponent.FindTextField;

/**
 *
 * @author Phan Qui Duc
 */
public class ToolBar extends javax.swing.JPanel {

    /**
     * Creates new form ToolBar
     */
    public ToolBar () {
        initComponents();
        init();
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    public FindTextField getFindTextField () {
        return findTextField;
    }

    public void setFindTextField (FindTextField findTextField) {
        this.findTextField = findTextField;
    }

    public UserPanel getUserPanel () {
        return userPanel;
    }

    public void setUserPanel (UserPanel userPanel) {
        this.userPanel = userPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findTextField = new swing.utilcomponent.FindTextField();
        userPanel = new swing.swavecomponent.UserPanel();

        setMaximumSize(new java.awt.Dimension(1283, 100));
        setMinimumSize(new java.awt.Dimension(1283, 100));
        setPreferredSize(new java.awt.Dimension(1283, 100));

        findTextField.setColor1(new java.awt.Color(255, 255, 255));
        findTextField.setColor2(new java.awt.Color(255, 255, 255));
        findTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                findTextFieldCaretUpdate(evt);
            }
        });

        userPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userPanelMouseClicked

    private void findTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_findTextFieldCaretUpdate

    }//GEN-LAST:event_findTextFieldCaretUpdate

    private void init () {
        setBackground(new Color(0, 0, 0, 255));
//        findTextField.addFocusListener(new FocusListener() {
//            @Override
//            public void focusGained (FocusEvent e) {
//                if (findTextField.getText().equals("Bạn muốn nghe gì?")) {
//                    findTextField.setText("");
//                }
//            }
//
//            @Override
//            public void focusLost (FocusEvent e) {
//                if (findTextField.getText().isEmpty()) {
//                    findTextField.setText("Bạn muốn nghe gì?");
//                }
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.utilcomponent.FindTextField findTextField;
    private swing.swavecomponent.UserPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
