/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing.swavecomponent;

import swave.MainFrame;

/**
 *
 * @author Phan Qui Duc
 */
public class UserTool extends javax.swing.JPanel {

    /**
     * Creates new form UserTool
     */
    private MainFrame mf;

    public UserTool () {
        initComponents();
        init();
    }
    
    public UserTool (MainFrame mainFrame) {
        mf = mainFrame;
        initComponents();
        init();
    }

    public MainFrame getMf() {
        return mf;
    }

    public void setMf(MainFrame mf) {
        this.mf = mf;
    }

    public UserToolComponent getPnlAdminTool () {
        return pnlAdminTool;
    }

    public void setPnlAdminTool (UserToolComponent pnlAdminTool) {
        this.pnlAdminTool = pnlAdminTool;
    }

    public UserToolComponent getPnlIntroduction () {
        return pnlIntroduction;
    }

    public void setPnlIntroduction (UserToolComponent pnlIntroduction) {
        this.pnlIntroduction = pnlIntroduction;
    }

    public UserToolComponent getPnlLogout () {
        return pnlLogout;
    }

    public void setPnlLogout (UserToolComponent pnlLogout) {
        this.pnlLogout = pnlLogout;
    }

    public UserToolComponent getPnlPersonalInfo () {
        return pnlPersonalInfo;
    }

    public void setPnlPersonalInfo (UserToolComponent pnlPersonalInfo) {
        this.pnlPersonalInfo = pnlPersonalInfo;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPersonalInfo = new swing.swavecomponent.UserToolComponent();
        pnlAdminTool = new swing.swavecomponent.UserToolComponent();
        pnlIntroduction = new swing.swavecomponent.UserToolComponent();
        pnlLogout = new swing.swavecomponent.UserToolComponent();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(248, 200));
        setMinimumSize(new java.awt.Dimension(248, 150));
        setPreferredSize(new java.awt.Dimension(248, 200));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        add(pnlPersonalInfo);
        add(pnlAdminTool);
        add(pnlIntroduction);
        add(pnlLogout);
    }// </editor-fold>//GEN-END:initComponents

    private void init(){
        pnlPersonalInfo.getLblPanelName().setText("Thông tin cá nhân");
        pnlAdminTool.getLblPanelName().setText("Công cụ cho Admin");
        pnlIntroduction.getLblPanelName().setText("Giới thiệu");
        pnlLogout.getLblPanelName().setText("Đăng xuất");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.swavecomponent.UserToolComponent pnlAdminTool;
    private swing.swavecomponent.UserToolComponent pnlIntroduction;
    private swing.swavecomponent.UserToolComponent pnlLogout;
    private swing.swavecomponent.UserToolComponent pnlPersonalInfo;
    // End of variables declaration//GEN-END:variables
}
