/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing.swavecomponent;

import swing.glasspanepopup.GlassPanePopup;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JLabel;

/**
 *
 * @author Phan Qui Duc
 */
public class UserPanel extends javax.swing.JPanel {

    private int roundRadius = 49;

    /**
     * Creates new form UserPanel
     */
    public UserPanel () {
        initComponents();
        init();
    }

    public int getRoundRadius () {
        return roundRadius;
    }

    public void setRoundRadius (int roundRadius) {
        this.roundRadius = roundRadius;
    }

    public JLabel getLblAvt () {
        return lblAvt;
    }

    public void setLblAvt (JLabel lblAvt) {
        this.lblAvt = lblAvt;
    }

    public JLabel getLblButton () {
        return lblButton;
    }

    public void setLblButton (JLabel lblButton) {
        this.lblButton = lblButton;
    }

    public JLabel getLblName () {
        return lblName;
    }

    public void setLblName (JLabel lblName) {
        this.lblName = lblName;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvt = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(67, 67, 67));
        setMaximumSize(new java.awt.Dimension(248, 49));
        setMinimumSize(new java.awt.Dimension(248, 49));
        setPreferredSize(new java.awt.Dimension(248, 49));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 12));

        lblAvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/avtMini.png"))); // NOI18N
        add(lblAvt);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Họ và Tên");
        lblName.setMaximumSize(new java.awt.Dimension(130, 20));
        lblName.setMinimumSize(new java.awt.Dimension(130, 20));
        lblName.setPreferredSize(new java.awt.Dimension(130, 20));
        add(lblName);

        lblButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/downButton.png"))); // NOI18N
        add(lblButton);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    
    private void init () {
        setOpaque(false);
    }

    @Override
    protected void paintComponent (Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        Area area = new Area(createRoundTopLeft());
        area.intersect(new Area(createRoundBottomLeft()));
        g2.fill(area);
        g2.dispose();
        super.paintComponent(g);
    }

    private Shape createRoundTopLeft () {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundRadius);
        int roundY = Math.min(height, roundRadius);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(roundX / 2, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, width - roundX / 2, width, height - roundY / 2)));
        return area;
    }

    private Shape createRoundBottomLeft () {
        int width = getWidth();
        int height = getHeight();
        int roundX = Math.min(width, roundRadius);
        int roundY = Math.min(height, roundRadius);
        Area area = new Area(new RoundRectangle2D.Double(0, 0, width, height, roundX, roundY));
        area.add(new Area(new Rectangle2D.Double(roundX / 2, 0, width - roundX / 2, height)));
        area.add(new Area(new Rectangle2D.Double(0, 0, width, height - roundY / 2)));
        return area;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvt;
    private javax.swing.JLabel lblButton;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
