/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import Vu.ui.UserManagermentPanel;
import component.ButtonDelete;
import component.ToggleButton;
import components.borderImage;
import dao.AccountDAO;
import dao.UserDAO;
import entity.Account;
import entity.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import utils.MsgBox;

/**
 *
 * @author CAMERA VIET PHAT
 */
public class AccountItem extends javax.swing.JPanel {

    private Font font = new Font("Roboto", Font.BOLD, 16);
    private int sizeImage[] = {35, 35};

    private UserDAO udao = new UserDAO();
    private AccountDAO adao = new AccountDAO();
    

    public ButtonDelete getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(ButtonDelete btnDelete) {
        this.btnDelete = btnDelete;
    }

    public borderImage getLblAvatar() {
        return lblAvatar;
    }

    public void setLblAvatar(borderImage lblAvatar) {
        this.lblAvatar = lblAvatar;
    }

    public JLabel getLblSTT() {
        return lblSTT;
    }

    public void setLblSTT(JLabel lblSTT) {
        this.lblSTT = lblSTT;
    }

    public JLabel getLblUserID() {
        return lblUserID;
    }

    public void setLblUserID(JLabel lblUserID) {
        this.lblUserID = lblUserID;
    }

    public JLabel getLblUserName() {
        return lblUserName;
    }

    public void setLblUserName(JLabel lblUserName) {
        this.lblUserName = lblUserName;
    }

    public ToggleButton getTgbtnStatus() {
        return tgbtnStatus;
    }

    public void setTgbtnStatus(ToggleButton tgbtnStatus) {
        this.tgbtnStatus = tgbtnStatus;
    }

    /**
     * Creates new form AccountItem
     */
    public AccountItem() {
        initComponents();
        setBackground(Color.BLACK);
        lblSTT.setFont(font);
        lblSTT.setForeground(Color.WHITE);
        lblUserID.setFont(font);
        lblUserID.setForeground(Color.WHITE);
        lblUserName.setFont(font);
        lblUserName.setForeground(Color.WHITE);
        pnlSTT.setBackground(Color.BLACK);
        pnlUserName.setBackground(Color.BLACK);
        pnlUserID.setBackground(Color.BLACK);
        pnlStatus.setBackground(Color.BLACK);
        pnlDelete.setBackground(Color.BLACK);
        lblAvatar.setSizeImage(sizeImage);
    }

    public void setDataAccount(Account data) {
        User user = udao.selectById(data.getUserID());
        lblAvatar.setIcon(new ImageIcon(getClass().getResource("/img/avt/" +user.getAvt())));
//        lblAvatar.setIcon(new ImageIcon(getClass().getResource("/img/playlist.png")));
        lblUserName.setText(user.getFullname());
        lblUserID.setText(data.getUserID());
        tgbtnStatus.setSelected(data.isStatus() ? false : true);
    }

    public void changeStatus() {
        if (tgbtnStatus.isSelected()) {
            tgbtnStatus.setForeground(tgbtnStatus.getColor1());
            tgbtnStatus.setColor1(tgbtnStatus.getColor3());
            tgbtnStatus.setText("Vô hiệu hóa");
        } else {
            tgbtnStatus.setForeground(tgbtnStatus.getColor2());
            tgbtnStatus.setColor1(Color.decode("#FFFFFF"));
            tgbtnStatus.setText("Hiệu lực");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSTT = new javax.swing.JPanel();
        lblSTT = new javax.swing.JLabel();
        pnlUserName = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblAvatar = new components.borderImage();
        pnlUserID = new javax.swing.JPanel();
        lblUserID = new javax.swing.JLabel();
        pnlStatus = new javax.swing.JPanel();
        tgbtnStatus = new component.ToggleButton();
        pnlDelete = new javax.swing.JPanel();
        btnDelete = new component.ButtonDelete();

        setPreferredSize(new java.awt.Dimension(1170, 70));

        lblSTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSTT.setText("1");

        javax.swing.GroupLayout pnlSTTLayout = new javax.swing.GroupLayout(pnlSTT);
        pnlSTT.setLayout(pnlSTTLayout);
        pnlSTTLayout.setHorizontalGroup(
            pnlSTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSTT, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSTTLayout.setVerticalGroup(
            pnlSTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblUserName.setText("Phan Quí Đức");

        lblAvatar.setPreferredSize(new java.awt.Dimension(35, 35));
        lblAvatar.setLayout(null);

        javax.swing.GroupLayout pnlUserNameLayout = new javax.swing.GroupLayout(pnlUserName);
        pnlUserName.setLayout(pnlUserNameLayout);
        pnlUserNameLayout.setHorizontalGroup(
            pnlUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUserNameLayout.setVerticalGroup(
            pnlUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUserID.setText("ducpq123");

        javax.swing.GroupLayout pnlUserIDLayout = new javax.swing.GroupLayout(pnlUserID);
        pnlUserID.setLayout(pnlUserIDLayout);
        pnlUserIDLayout.setHorizontalGroup(
            pnlUserIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlUserIDLayout.setVerticalGroup(
            pnlUserIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tgbtnStatus.setText("Hiệu lực");
        tgbtnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtnStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStatusLayout = new javax.swing.GroupLayout(pnlStatus);
        pnlStatus.setLayout(pnlStatusLayout);
        pnlStatusLayout.setHorizontalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgbtnStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlStatusLayout.setVerticalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tgbtnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlDelete.setPreferredSize(new java.awt.Dimension(100, 50));

        btnDelete.setText("Xóa");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDeleteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDeleteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlSTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pnlDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(pnlUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tgbtnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtnStatusActionPerformed
        if (tgbtnStatus.isSelected()) {
            if (MsgBox.confirm(this, "Bạn thực sự muốn vô hiệu hóa tài khoản này?")) {
                try {
                    adao.updateStatus(lblUserID.getText(), false);
                    MsgBox.alert(this, "Vô hiệu hóa thành công!");
                    tgbtnStatus.setForeground(tgbtnStatus.getColor1());
                    tgbtnStatus.setColor1(tgbtnStatus.getColor3());
                    tgbtnStatus.setText("Vô hiệu hóa");
                } catch (HeadlessException e) {
                    MsgBox.alert(this, "Vô hiệu hóa thất bại!");
                }
            }
        } else {
            if (MsgBox.confirm(this, "Bạn thực sự muốn bật trạng thái hiệu lực cho tài khoản này?")) {
                try {
                    adao.updateStatus(lblUserID.getText(), true);
                    MsgBox.alert(this, "Bật trạng thái hiệu lực thành công!");
                    tgbtnStatus.setForeground(tgbtnStatus.getColor2());
                    tgbtnStatus.setColor1(Color.decode("#FFFFFF"));
                    tgbtnStatus.setText("Hiệu lực");
                } catch (HeadlessException e) {
                    MsgBox.alert(this, "Bật trạng thái hiệu lực thất bại!");
                }
            }
        }
    }//GEN-LAST:event_tgbtnStatusActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        if (MsgBox.confirm(this, "Bạn thực sự muốn xóa tài khoản này?")) {
            try {
                adao.delete(getLblUserID().getText());
                UserManagermentPanel.adminFrame.getUserManagermentPanel().getAccountListPane().removeAll();
                UserManagermentPanel.adminFrame.getUserManagermentPanel().getAccountListPane().loadData();
                UserManagermentPanel.adminFrame.getUserManagermentPanel().getAccountListPane().repaint();
                MsgBox.alert(this, "Xóa thành công!");
            } catch (HeadlessException e) {
                MsgBox.alert(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btnDeleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.ButtonDelete btnDelete;
    private components.borderImage lblAvatar;
    private javax.swing.JLabel lblSTT;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlSTT;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JPanel pnlUserID;
    private javax.swing.JPanel pnlUserName;
    private component.ToggleButton tgbtnStatus;
    // End of variables declaration//GEN-END:variables
}
