/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import component.EventItem;
import dao.AccountDAO;
import entity.Account;
import entity.User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author CAMERA VIET PHAT
 */
public class AccountList extends javax.swing.JPanel {

    private List<Account> aList;
    private AccountDAO adao = new AccountDAO();

    public JPanel getPnlAccountList() {
        return pnlAccountList;
    }

    public void setPnlAccountList(JPanel pnlAccountList) {
        this.pnlAccountList = pnlAccountList;
    }
    
    /**
     * Creates new form AccountList
     */
    public AccountList() {
        initComponents();
        setBackground(Color.BLACK);
        jscAccountList.setBackground(Color.BLACK);
        pnlAccountList.setBackground(Color.BLACK);
        jscAccountList.getViewport().setBackground(new Color(255, 255, 255, 0));
    }
    
    public void addAccount(Account data) {
        AccountItem item = new AccountItem();
        item.setDataAccount(data);
        item.getLblSTT().setText(String.valueOf(pnlAccountList.getComponentCount() + 1));
        item.changeStatus();
        pnlAccountList.add(item);
        
        if (pnlAccountList.getComponentCount() > 7) {
            pnlAccountList.setPreferredSize(new Dimension(1170, pnlAccountList.getHeight() + 70));
        }
        validate();
        pnlAccountList.revalidate();
    }
    
    public void removeAll() {
        pnlAccountList.removeAll();
        pnlAccountList.setPreferredSize(new Dimension(1170, 530));
    }
    
    public void loadData() {
        aList = adao.selectAll();
        for (int i = 0; i < aList.size(); i++) {
            this.addAccount(aList.get(i));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscAccountList = new javax.swing.JScrollPane();
        pnlAccountList = new javax.swing.JPanel();
        scrollBar1 = new components.ScrollBar();

        jscAccountList.setBackground(new java.awt.Color(255, 255, 255));
        jscAccountList.setBorder(null);
        jscAccountList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jscAccountList.setToolTipText("");
        jscAccountList.setHorizontalScrollBar(null);
        jscAccountList.setOpaque(false);
        jscAccountList.setPreferredSize(new java.awt.Dimension(1170, 530));
        jscAccountList.setVerticalScrollBar(scrollBar1);
        jscAccountList.setViewportView(null);

        pnlAccountList.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccountList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlAccountList.setMinimumSize(new java.awt.Dimension(10, 0));
        pnlAccountList.setOpaque(false);
        pnlAccountList.setPreferredSize(new java.awt.Dimension(1170, 530));
        pnlAccountList.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        jscAccountList.setViewportView(pnlAccountList);

        scrollBar1.setPreferredSize(new java.awt.Dimension(8, 508));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jscAccountList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscAccountList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jscAccountList;
    private javax.swing.JPanel pnlAccountList;
    private components.ScrollBar scrollBar1;
    // End of variables declaration//GEN-END:variables
}
