
package swing;

import component.ScrollBar;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import entity.PlayList;

/**
 *
 * @author NGUYEN VAN SI
 */
public class PlaylistSearch extends javax.swing.JPanel {

    /**
     * Creates new form PlayList
     */
    public PlaylistSearch() {
        initComponents();
        jscPlaylist.getViewport().setBackground(new Color(255, 255, 255, 0));
    }

    public void addPlayList(PlayList data) {
        PlaylistItem item = new PlaylistItem(data);
        pnlPlaylist.add(item);
        System.out.println(pnlPlaylist.getComponentCount());
        if (((pnlPlaylist.getComponentCount() - 1) != 0) && ((pnlPlaylist.getComponentCount() > 4))) {
            pnlPlaylist.setPreferredSize(new Dimension(pnlPlaylist.getWidth() + 276, 300));
            validate();
        }
        repaint();
        pnlPlaylist.revalidate();
    }

    public JScrollPane getJscPlaylist() {
        return jscPlaylist;
    }

    public void setJscPlaylist(JScrollPane jscPlaylist) {
        this.jscPlaylist = jscPlaylist;
    }

    public JPanel getPnlPlaylist() {
        return pnlPlaylist;
    }

    public void setPnlPlaylist(JPanel pnlPlaylist) {
        this.pnlPlaylist = pnlPlaylist;
    }

    public ScrollBar getScrollBar1() {
        return scrollBar1;
    }

    public void setScrollBar1(ScrollBar scrollBar1) {
        this.scrollBar1 = scrollBar1;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscPlaylist = new javax.swing.JScrollPane();
        pnlPlaylist = new javax.swing.JPanel();
        scrollBar1 = new component.ScrollBar();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1273, 510));

        jscPlaylist.setBackground(new java.awt.Color(255, 255, 255));
        jscPlaylist.setBorder(null);
        jscPlaylist.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jscPlaylist.setHorizontalScrollBar(scrollBar1);
        jscPlaylist.setPreferredSize(new java.awt.Dimension(1270, 330));

        pnlPlaylist.setBackground(new java.awt.Color(255, 255, 255));
        pnlPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPlaylist.setOpaque(false);
        pnlPlaylist.setPreferredSize(new java.awt.Dimension(1210, 300));
        pnlPlaylist.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 0));
        jscPlaylist.setViewportView(pnlPlaylist);

        scrollBar1.setForeground(new java.awt.Color(51, 51, 51));
        scrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scrollBar1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jscPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(432, 432, 432))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jscPlaylist;
    private javax.swing.JPanel pnlPlaylist;
    private component.ScrollBar scrollBar1;
    // End of variables declaration//GEN-END:variables
}
