
package swing;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import swave.MainFrame;
/**
 *
 * @author NGUYEN VAN SI
 */
public class PlaylistPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlayList
     */
    public PlaylistPanel() {
        initComponents();
        pnlPlaylist.setBackground(new Color(255, 255, 255, 0));
        jscPlaylist.getViewport().setBackground(new Color(255, 255, 255, 0));
        
    }

    public void addPlayList(entity.PlayList data,  MainFrame main) {
        PlaylistItem item = new PlaylistItem();
        item.loadData(data);
        item.setMain(main);
        pnlPlaylist.add(item);
        if (((pnlPlaylist.getComponentCount() - 1) != 0) && ((pnlPlaylist.getComponentCount()-1) % 4 == 0)) {
            pnlPlaylist.setPreferredSize(new Dimension(1220, pnlPlaylist.getHeight() + 330));
            validate();
        }
        repaint();
        pnlPlaylist.revalidate();
    }

    public JPanel getPnlPlaylist() {
        return pnlPlaylist;
    }

    public void setPnlPlaylist(JPanel pnlPlaylist) {
        this.pnlPlaylist = pnlPlaylist;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscPlaylist = new javax.swing.JScrollPane();
        pnlPlaylist = new javax.swing.JPanel();
        scrollBar1 = new component.ScrollBar();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1273, 510));

        jscPlaylist.setBackground(new java.awt.Color(255, 255, 255));
        jscPlaylist.setBorder(null);
        jscPlaylist.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jscPlaylist.setHorizontalScrollBar(null);
        jscPlaylist.setVerticalScrollBar(scrollBar1);

        pnlPlaylist.setBackground(new java.awt.Color(255, 255, 255));
        pnlPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPlaylist.setOpaque(false);
        pnlPlaylist.setPreferredSize(new java.awt.Dimension(1210, 330));
        pnlPlaylist.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 30));
        jscPlaylist.setViewportView(pnlPlaylist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jscPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jscPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jscPlaylist;
    private javax.swing.JPanel pnlPlaylist;
    private component.ScrollBar scrollBar1;
    // End of variables declaration//GEN-END:variables
}
