package swing;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import entity.PlayList;
import model.borderImage;

/**
 *
 * @author NGUYEN VAN SI
 */
public class PlaylistItem extends javax.swing.JPanel {

    /**
     * Creates new form PlaylistItem
     */
    PlayList data;
    
    public PlaylistItem(PlayList data) {
        this.data = data;
        initComponents();
        setOpaque(false);
        lblAVT.setIcon(data.toIcon());
        lblPlaylistName.setText(data.getPlaylistName());
        lblPlaylistAuthor.setText("By " + data.getUserID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAVT = new model.borderImage();
        lblPlaylistName = new javax.swing.JLabel();
        lblPlaylistAuthor = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(256, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAVT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAVTMouseClicked(evt);
            }
        });
        add(lblAVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 220, 220));

        lblPlaylistName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPlaylistName.setForeground(new java.awt.Color(253, 178, 255));
        lblPlaylistName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaylistName.setText("Playlist name");
        lblPlaylistName.setPreferredSize(new java.awt.Dimension(151, 29));
        add(lblPlaylistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 180, -1));

        lblPlaylistAuthor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPlaylistAuthor.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaylistAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaylistAuthor.setText("By Author");
        lblPlaylistAuthor.setPreferredSize(new java.awt.Dimension(200, 29));
        add(lblPlaylistAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAVTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAVTMouseClicked
       
    }//GEN-LAST:event_lblAVTMouseClicked

    public PlayList getData() {
        return data;
    }

    public void setData(PlayList data) {
        this.data = data;
    }

    public borderImage getLblAVT() {
        return lblAVT;
    }

    public void setLblAVT(borderImage lblAVT) {
        this.lblAVT = lblAVT;
    }

    public JLabel getLblPlaylistAuthor() {
        return lblPlaylistAuthor;
    }

    public void setLblPlaylistAuthor(JLabel lblPlaylistAuthor) {
        this.lblPlaylistAuthor = lblPlaylistAuthor;
    }

    public JLabel getLblPlaylistName() {
        return lblPlaylistName;
    }

    public void setLblPlaylistName(JLabel lblPlaylistName) {
        this.lblPlaylistName = lblPlaylistName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private model.borderImage lblAVT;
    private javax.swing.JLabel lblPlaylistAuthor;
    private javax.swing.JLabel lblPlaylistName;
    // End of variables declaration//GEN-END:variables
}
