package swing;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;
import entity.Song;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Map;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.UnsupportedAudioFileException;
import model.borderImage;
import utils.TAudioFileFormat;

/**
 *
 * @author NGUYEN VAN SI
 */
public class SongItem extends javax.swing.JPanel {

    /**
     * Creates new form Song
     */
    public boolean running = false;
    public Song data;
    public int minutetotalLength;
    public int secondTotalLength;

    public SongItem() {
        initComponents();
        this.setBackground(new Color(255, 255, 255, 0));
        lblStart.setVisible(false);
        lblWave.setVisible(false);
        lblIconLove.setVisible(false);
    }

    public void setDataSong(Song data) throws UnsupportedAudioFileException, IOException, URISyntaxException {
        this.data = data;
        lblIconPlay.setText("" + data.getSongID());
        lblIconSong.setIcon(data.toIcon());
        lblNamSong.setText(data.getNameSong());
//        getTimeSong();
        lblTime.setText("0" + minutetotalLength + ":" + "0" + secondTotalLength);
    }

    public void selectRunning(boolean running) {
        if (running) {
            this.setBackground(new Color(93, 20, 118));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIcon = new javax.swing.JPanel();
        lblIconPlay = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblWave = new javax.swing.JLabel();
        pnlSongName = new javax.swing.JPanel();
        lblIconSong = new model.borderImage();
        lblNamSong = new javax.swing.JLabel();
        pnlLove = new javax.swing.JPanel();
        lblIconLove = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIcon.setOpaque(false);
        pnlIcon.setPreferredSize(new java.awt.Dimension(112, 47));
        pnlIcon.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        lblIconPlay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIconPlay.setForeground(new java.awt.Color(199, 199, 199));
        lblIconPlay.setPreferredSize(new java.awt.Dimension(35, 44));
        pnlIcon.add(lblIconPlay);

        lblStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        lblStart.setPreferredSize(new java.awt.Dimension(35, 28));
        lblStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStartMouseClicked(evt);
            }
        });
        pnlIcon.add(lblStart);

        lblWave.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblWave.setForeground(new java.awt.Color(255, 255, 255));
        lblWave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangchay.gif"))); // NOI18N
        lblWave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWaveMouseClicked(evt);
            }
        });
        pnlIcon.add(lblWave);

        add(pnlIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 11, 112, 47));

        pnlSongName.setOpaque(false);
        pnlSongName.setPreferredSize(new java.awt.Dimension(496, 50));
        pnlSongName.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        lblIconSong.setPreferredSize(new java.awt.Dimension(50, 50));
        lblIconSong.setSizeImage(new int[] {50, 50});
        pnlSongName.add(lblIconSong);

        lblNamSong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamSong.setForeground(new java.awt.Color(199, 199, 199));
        lblNamSong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNamSong.setPreferredSize(new java.awt.Dimension(421, 50));
        pnlSongName.add(lblNamSong);

        add(pnlSongName, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 0, 496, 70));

        pnlLove.setOpaque(false);
        pnlLove.setPreferredSize(new java.awt.Dimension(194, 50));
        pnlLove.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 15));

        lblIconLove.setPreferredSize(new java.awt.Dimension(25, 22));
        lblIconLove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconLoveMouseEntered(evt);
            }
        });
        pnlLove.add(lblIconLove);

        add(pnlLove, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 194, 50));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(199, 199, 199));
        lblTime.setPreferredSize(new java.awt.Dimension(141, 50));
        jPanel1.add(lblTime);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 141, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void lblWaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWaveMouseClicked
        lblWave.setVisible(false);
        lblStart.setVisible(true);
        running = false;
    }//GEN-LAST:event_lblWaveMouseClicked

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        try {
            if (((evt.getX() < this.getLocation().getX()) || (evt.getX() > this.getLocation().getX()))
                    && (this.getMousePosition().getX() < this.getLocation().getX())) {
            }
        } catch (Exception e) {
            if (isRunning()) {
                this.setBackground(new Color(93, 20, 118));
            } else {
                this.setBackground(new Color(255, 255, 255, 0));
                lblIconLove.setVisible(false);
            }

            lblIconPlay.setVisible(!running);
            lblStart.setVisible(false);
            lblNamSong.setForeground(new Color(199, 199, 199));
            lblIconPlay.setForeground(new Color(199, 199, 199));
            lblTime.setForeground(new Color(199, 199, 199));
        }

    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(new Color(119, 88, 130));
        lblIconPlay.setVisible(false);
        lblStart.setVisible(!running);
        lblNamSong.setForeground(Color.white);
        lblIconPlay.setForeground(Color.white);
        lblTime.setForeground(Color.white);
        lblIconLove.setVisible(true);
    }//GEN-LAST:event_formMouseEntered

    private void lblStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseClicked
    }//GEN-LAST:event_lblStartMouseClicked

    private void lblIconLoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconLoveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconLoveMouseEntered

    public boolean isRunning() {
        return running;
    }

    public void setRunning(boolean running) {
        this.running = running;
        repaint();
    }

    public Song getData() {
        return data;
    }

    public void setData(Song data) {
        this.data = data;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLblIconLove() {
        return lblIconLove;
    }

    public void setLblIconLove(JLabel lblIconLove) {
        this.lblIconLove = lblIconLove;
    }

    public JLabel getLblIconPlay() {
        return lblIconPlay;
    }

    public void setLblIconPlay(JLabel lblIconPlay) {
        this.lblIconPlay = lblIconPlay;
    }

    public borderImage getLblIconSong() {
        return lblIconSong;
    }

    public void setLblIconSong(borderImage lblIconSong) {
        this.lblIconSong = lblIconSong;
    }

    public JLabel getLblNamSong() {
        return lblNamSong;
    }

    public void setLblNamSong(JLabel lblNamSong) {
        this.lblNamSong = lblNamSong;
    }

    public JLabel getLblStart() {
        return lblStart;
    }

    public void setLblStart(JLabel lblStart) {
        this.lblStart = lblStart;
    }

    public JLabel getLblTime() {
        return lblTime;
    }

    public void setLblTime(JLabel lblTime) {
        this.lblTime = lblTime;
    }

    public JLabel getLblWave() {
        return lblWave;
    }

    public void setLblWave(JLabel lblWave) {
        this.lblWave = lblWave;
    }

    public JPanel getPnlIcon() {
        return pnlIcon;
    }

    public void setPnlIcon(JPanel pnlIcon) {
        this.pnlIcon = pnlIcon;
    }

    public JPanel getPnlLove() {
        return pnlLove;
    }

    public void setPnlLove(JPanel pnlLove) {
        this.pnlLove = pnlLove;
    }

    public JPanel getPnlSongName() {
        return pnlSongName;
    }

    public void setPnlSongName(JPanel pnlSongName) {
        this.pnlSongName = pnlSongName;
    }

    public void getTimeSong() throws UnsupportedAudioFileException, IOException, URISyntaxException {
        File f = new File( getClass().getResource(data.getFileSong()).getFile());
        AudioFileFormat fileFormat = AudioSystem.getAudioFileFormat(f);
        if (!(fileFormat instanceof TAudioFileFormat)) {
            Map<?, ?> properties = ((TAudioFileFormat) fileFormat).properties();
            String key = "duration";
            Long microseconds = (Long) properties.get(key);
            int mili = (int) (microseconds / 1000);
            int sec = (mili / 1000) % 60;
            int min = (mili / 1000) / 60;
            minutetotalLength = min;
            secondTotalLength = sec;
        } else {
            throw new UnsupportedAudioFileException();
        }
        System.out.println(data.getFileSong());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIconLove;
    private javax.swing.JLabel lblIconPlay;
    private model.borderImage lblIconSong;
    private javax.swing.JLabel lblNamSong;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWave;
    private javax.swing.JPanel pnlIcon;
    private javax.swing.JPanel pnlLove;
    private javax.swing.JPanel pnlSongName;
    // End of variables declaration//GEN-END:variables

}
