/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import components.ScrollBar;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import entity.Song;

/**
 *
 * @author CAMERA VIET PHAT
 */
public class SongOfSearchAll extends javax.swing.JPanel {

    public static ArrayList<Song> list = new ArrayList<>();
    
    /**
     * Creates new form PlaylistOfSearchAll
     */
    public SongOfSearchAll() {
        initComponents();
        setBackground(Color.BLACK);
        lblTitle.setForeground(Color.WHITE);
        jscSong.getViewport().setBackground(new Color(255, 255, 255, 0));
    }

    public void addSong(Song data) {
        SongItemSearch item = new SongItemSearch(data);
        pnlSong.add(item);
//        if (pnlSong.getComponentCount() == 5){
//            pnlSong.setPreferredSize(new Dimension(1320, 300));
//        }
        if (((pnlSong.getComponentCount() - 1) != 0) && ((pnlSong.getComponentCount() - 1 > 4))) {
            pnlSong.setPreferredSize(new Dimension(pnlSong.getWidth() + 256, 300));
            validate();
        }
        repaint();
        pnlSong.revalidate();
        pnlSong.repaint();
    }

    public JScrollPane getJscSong() {
        return jscSong;
    }

    public void setJscSong(JScrollPane jscSong) {
        this.jscSong = jscSong;
    }

    public JPanel getPnlSong() {
        return pnlSong;
    }

    public void setPnlSong(JPanel pnlSong) {
        this.pnlSong = pnlSong;
    }

    public ScrollBar getScrollBar1() {
        return scrollBar1;
    }

    public void setScrollBar1(ScrollBar scrollBar1) {
        this.scrollBar1 = scrollBar1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscSong = new javax.swing.JScrollPane();
        pnlSong = new javax.swing.JPanel();
        scrollBar1 = new components.ScrollBar();
        lblTitle = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1239, 360));

        jscSong.setBackground(new java.awt.Color(255, 255, 255));
        jscSong.setBorder(null);
        jscSong.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jscSong.setHorizontalScrollBar(scrollBar1);
        jscSong.setPreferredSize(new java.awt.Dimension(1239, 300));

        pnlSong.setBackground(new java.awt.Color(255, 255, 255));
        pnlSong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSong.setOpaque(false);
        pnlSong.setPreferredSize(new java.awt.Dimension(1239, 300));
        pnlSong.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 30));
        jscSong.setViewportView(pnlSong);

        scrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        lblTitle.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lblTitle.setText("Song");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(0, 0, 0)
                .addComponent(jscSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jscSong;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlSong;
    private components.ScrollBar scrollBar1;
    // End of variables declaration//GEN-END:variables
}
