/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vu.ui;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class AdminToolDialog extends javax.swing.JDialog {

    /**
     * Creates new form AdminToolDialog
     */
    private CardLayout c;

    public AdminToolDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        c = (CardLayout) pnlChange.getLayout();
        c.show(pnlChange, "cardUS");
        lblAC.setForeground(Color.pink);
    }

    private void init(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose = new javax.swing.JLabel();
        lblTK = new javax.swing.JLabel();
        lblComment = new javax.swing.JLabel();
        lblSong = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        pnlChange = new javax.swing.JPanel();
        userManagermentPanel = new Vu.ui.UserManagermentPanel();
        uncensorSongPane = new Vu.ui.UncensorSongPane();
        reportCommentPanel = new Vu.ui.ReportCommentPanel();
        allCommentPane = new Vu.ui.AllCommentPane();
        statisticLikePanel = new Vu.ui.StatisticLikePanel();
        statisticViewPanel = new Vu.ui.StatisticViewPanel();
        menuBar1 = new AdminToolUtils.MenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("THOÁT");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 310, 50));

        lblTK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTK.setForeground(new java.awt.Color(255, 255, 255));
        lblTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTK.setText("THỐNG KÊ");
        lblTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTKMouseClicked(evt);
            }
        });
        getContentPane().add(lblTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 310, 50));

        lblComment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblComment.setForeground(new java.awt.Color(255, 255, 255));
        lblComment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComment.setText("KIỂM DUYỆT BÌNH LUẬN");
        lblComment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCommentMouseClicked(evt);
            }
        });
        getContentPane().add(lblComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 310, 50));

        lblSong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSong.setForeground(new java.awt.Color(255, 255, 255));
        lblSong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSong.setText("KIỂM DUYỆT BÀI HÁT");
        lblSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSongMouseEntered(evt);
            }
        });
        getContentPane().add(lblSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 50));

        lblAC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAC.setForeground(new java.awt.Color(255, 255, 255));
        lblAC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAC.setText("QUẢN LÍ TÀI KHOẢN");
        lblAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblACMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblACMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblACMouseExited(evt);
            }
        });
        getContentPane().add(lblAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 310, 50));

        pnlChange.setBackground(new java.awt.Color(36, 36, 36));
        pnlChange.setPreferredSize(new java.awt.Dimension(1213, 807));
        pnlChange.setLayout(new java.awt.CardLayout());
        pnlChange.add(userManagermentPanel, "cardUS");
        pnlChange.add(uncensorSongPane, "cardUCS");
        pnlChange.add(reportCommentPanel, "cardRM");
        pnlChange.add(allCommentPane, "cardAM");
        pnlChange.add(statisticLikePanel, "cardSL");
        pnlChange.add(statisticViewPanel, "cardSV");

        getContentPane().add(pnlChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 0, 1219, -1));
        getContentPane().add(menuBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblACMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblACMouseEntered

    }//GEN-LAST:event_lblACMouseEntered

    private void lblACMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblACMouseExited

    }//GEN-LAST:event_lblACMouseExited

    private void lblSongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSongMouseEntered

    }//GEN-LAST:event_lblSongMouseEntered

    private void lblACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblACMouseClicked
        lblAC.setForeground(Color.PINK);
        lblSong.setForeground(Color.white);
        lblComment.setForeground(Color.white);
        lblTK.setForeground(Color.white);
        c.show(pnlChange, "cardUS");

    }//GEN-LAST:event_lblACMouseClicked

    private void lblSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSongMouseClicked
        lblSong.setForeground(Color.PINK);
        lblAC.setForeground(Color.white);
        lblComment.setForeground(Color.white);
        lblTK.setForeground(Color.white);
        c.show(pnlChange, "cardUCS");
    }//GEN-LAST:event_lblSongMouseClicked

    private void lblCommentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCommentMouseClicked
        lblComment.setForeground(Color.PINK);
        lblAC.setForeground(Color.white);
        lblSong.setForeground(Color.white);
        lblTK.setForeground(Color.white);
        c.show(pnlChange, "cardAM");
    }//GEN-LAST:event_lblCommentMouseClicked

    private void lblTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTKMouseClicked
        lblTK.setForeground(Color.PINK);
        lblAC.setForeground(Color.white);
        lblSong.setForeground(Color.white);
        lblComment.setForeground(Color.white);
        c.show(pnlChange, "cardSL");
    }//GEN-LAST:event_lblTKMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminToolDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminToolDialog dialog = new AdminToolDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vu.ui.AllCommentPane allCommentPane;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblSong;
    private javax.swing.JLabel lblTK;
    private AdminToolUtils.MenuBar menuBar1;
    private javax.swing.JPanel pnlChange;
    private Vu.ui.ReportCommentPanel reportCommentPanel;
    private Vu.ui.StatisticLikePanel statisticLikePanel;
    private Vu.ui.StatisticViewPanel statisticViewPanel;
    private Vu.ui.UncensorSongPane uncensorSongPane;
    private Vu.ui.UserManagermentPanel userManagermentPanel;
    // End of variables declaration//GEN-END:variables
}
