/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vu.ui;

import AdminToolUtils.ListSongItemStatistic;
import dao.StatisticDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.io.IOException;
import java.util.ArrayList;
import javax.sound.sampled.UnsupportedAudioFileException;
import swing.utilcomponent.ScrollBarCustom;
import utils.MsgBox;

/**
 *
 * @author Admin
 */
public class StatisticLikePanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticLikePanel
     */
    private StatisticDAO statisticDAO = new StatisticDAO();

    public StatisticLikePanel() {
        initComponents();
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        fillStatisticSongLikes();
        pnlStatisticSong.setOpaque(true);
        pnlStatisticSong.setBackground(new Color(0, 0, 0, 255));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setBackground(new Color(0, 0, 0, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblNumber = new javax.swing.JLabel();
        lblSongName = new javax.swing.JLabel();
        lblStatistic = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlStatisticSong = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        lblListens = new javax.swing.JLabel();
        lblLikes = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(36, 36, 36));

        pnlTitle.setBackground(new java.awt.Color(36, 36, 36));
        pnlTitle.setPreferredSize(new java.awt.Dimension(1073, 52));

        lblNumber.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber.setText("STT");

        lblSongName.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblSongName.setForeground(new java.awt.Color(255, 255, 255));
        lblSongName.setText("Tên bài hát");

        lblStatistic.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblStatistic.setForeground(new java.awt.Color(255, 255, 255));
        lblStatistic.setText("Lượt tim");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(lblSongName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatistic)
                .addGap(237, 237, 237))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSongName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );

        jSeparator2.setBackground(new java.awt.Color(199, 199, 199));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlStatisticSong.setBackground(new java.awt.Color(36, 36, 36));
        pnlStatisticSong.setMaximumSize(new java.awt.Dimension(1240, 564));
        pnlStatisticSong.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(pnlStatisticSong);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(36, 36, 36));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Thống kê");

        jPanel11.setBackground(new java.awt.Color(36, 36, 36));
        jPanel11.setForeground(new java.awt.Color(36, 36, 36));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblListens.setBackground(new java.awt.Color(36, 36, 36));
        lblListens.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblListens.setForeground(new java.awt.Color(255, 255, 255));
        lblListens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListens.setText("Lượt nghe");
        lblListens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListensMouseClicked(evt);
            }
        });

        lblLikes.setBackground(new java.awt.Color(36, 36, 36));
        lblLikes.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblLikes.setForeground(new java.awt.Color(165, 43, 168));
        lblLikes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLikes.setText("Lượt tim");
        lblLikes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLikesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(lblListens, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLikes, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLikes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblListensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListensMouseClicked
        // TODO add your handling code here:
        lblLikes.setForeground(Color.white);
        lblListens.setForeground(new Color(165, 43, 168));
        lblStatistic.setText("Lượt nghe");
        fillStatisticSongListens();
        revalidate();
        repaint();

    }//GEN-LAST:event_lblListensMouseClicked

    private void lblLikesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLikesMouseClicked
        // TODO add your handling code here:
        lblListens.setForeground(Color.white);
        lblLikes.setForeground(new Color(165, 43, 168));
        lblStatistic.setText("Lượt tim");
        fillStatisticSongLikes();
        revalidate();
        repaint();
    }//GEN-LAST:event_lblLikesMouseClicked

    public void fillStatisticSongLikes() {
        pnlStatisticSong.removeAll();
        try {
            ArrayList<Object[]> list = (ArrayList<Object[]>) statisticDAO.getAllSongByLoves();
            for (Object[] song : list) {
                fillPnlListSong(song);
            }
            pnlStatisticSong.repaint();
            pnlStatisticSong.revalidate();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    public void fillStatisticSongListens() {
        pnlStatisticSong.removeAll();
        try {
            ArrayList<Object[]> list = (ArrayList<Object[]>) statisticDAO.getAllSongByListens();
            for (Object[] song : list) {
                fillPnlListSong(song);
            }
            repaint();
            revalidate();
            pnlStatisticSong.repaint();
            pnlStatisticSong.revalidate();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    public void fillPnlListSong(Object[] song) throws UnsupportedAudioFileException, IOException {
        // Fill pnlListSongDetails

        int position = pnlStatisticSong.getComponentCount();

        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = position;
        addSongToPnlListSong(song, gridBagConstraints);

        // 4 dòng dưới để khiến cho panel có height của các components nằm bên trong
        pnlStatisticSong.setPreferredSize(null);
        pnlStatisticSong.setMaximumSize(new Dimension(pnlStatisticSong.getMaximumSize().width, pnlStatisticSong.getPreferredSize().height));
        pnlStatisticSong.validate();
        pnlStatisticSong.repaint();

        pnlStatisticSong.setOpaque(true);
        pnlStatisticSong.setBackground(new Color(0, 0, 0, 255));

        // set height của scroll pane 
        jScrollPane1.setPreferredSize(new Dimension(pnlStatisticSong.getMaximumSize().width, 320));
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());

        jScrollPane1.setOpaque(false);
        jScrollPane1.setBackground(new Color(0, 0, 0, 255));
    }

    public void addSongToPnlListSong(Object[] song, GridBagConstraints gridBagConstraints) throws UnsupportedAudioFileException, IOException {
        ListSongItemStatistic listSongItemStatistic = new ListSongItemStatistic(song);
        listSongItemStatistic.getLblPosition().setText(String.valueOf(gridBagConstraints.gridy + 1));

        pnlStatisticSong.add(listSongItemStatistic, gridBagConstraints);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblLikes;
    private javax.swing.JLabel lblListens;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblSongName;
    private javax.swing.JLabel lblStatistic;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlStatisticSong;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
}
