/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vu.ui;



/**
 *
 * @author Admin
 */
public class Toolbar extends javax.swing.JPanel {

    /**
     * Creates new form Tab
     */
    public Toolbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUser = new javax.swing.JButton();
        btnSong = new javax.swing.JButton();
        btnComment = new javax.swing.JButton();
        btnStatistic = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        btnUser.setBackground(new java.awt.Color(0, 0, 0));
        btnUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnUser.setForeground(new java.awt.Color(199, 199, 199));
        btnUser.setText("QUẢN LÝ TÀI KHOẢN");
        btnUser.setBorder(null);
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSong.setBackground(new java.awt.Color(0, 0, 0));
        btnSong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSong.setForeground(new java.awt.Color(199, 199, 199));
        btnSong.setText("KIỂM DUYỆT BÀI HÁT");
        btnSong.setBorder(null);

        btnComment.setBackground(new java.awt.Color(0, 0, 0));
        btnComment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnComment.setForeground(new java.awt.Color(199, 199, 199));
        btnComment.setText("KIỂM SOÁT BÌNH LUẬN");
        btnComment.setBorder(null);
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });

        btnStatistic.setBackground(new java.awt.Color(0, 0, 0));
        btnStatistic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnStatistic.setForeground(new java.awt.Color(199, 199, 199));
        btnStatistic.setText("THỐNG KÊ");
        btnStatistic.setBorder(null);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(199, 199, 199));
        btnExit.setText("THOÁT KHỎI CÔNG CỤ");
        btnExit.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 57, 234));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/4x/logo1.png"))); // NOI18N
        jLabel1.setText("SWAVE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSong, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(btnComment, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(btnStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSong, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComment;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSong;
    private javax.swing.JButton btnStatistic;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
